# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export USER_CONFIG_HOME="$HOME/.config"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$USER_CONFIG_HOME/zsh/custom"

# Setup go path
export PATH=$PATH:"$(go env GOPATH)/bin"

git_config_target="$HOME/.gitconfig"
if [ -L ${git_config_target} ] ; then
  git_config="$USER_CONFIG_HOME/git/config"
   if [ ! -e ${git_config_target} ] ; then
      echo "Git config is broken, relinking"
      ln -sf ${git_config} ${git_config_target}
   fi
elif [ -e ${git_config_target} ] ; then
   echo "Git config exists but is not symlinked, overwriting"
   ln -sf ${git_config} ${git_config_target}
else
  echo "Git config is not linked, linking"
   ln -s ${git_config} ${git_config_target}
fi

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="dd/mm/yyyy"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
    git
    zsh-abbr
    zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_SE.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Abbreviations
export ABBR_QUIET=1
abbr -S k="gk8s"

abbr -S g="git"
abbr -S ga="git add"
abbr -S gc="git commit"
abbr -S gp="git push"
abbr -S gs="git status"

abbr -S l="lsd -l"
abbr -S la="lsd -la"

# zsh-syntax-highlighting
typeset -A ZSH_HIGHLIGHT_REGEXP
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main regexp)
# the next two lines must come after zsh-abbr
ZSH_HIGHLIGHT_REGEXP=('^[[:blank:][:space:]]*('${(j:|:)${(k)ABBR_REGULAR_USER_ABBREVIATIONS}}')$' fg=blue)
ZSH_HIGHLIGHT_REGEXP+=('\<('${(j:|:)${(k)ABBR_GLOBAL_USER_ABBREVIATIONS}}')$' fg=yellow)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f "$USER_CONFIG_HOME/zsh/p10k.zsh" ]] || source "$USER_CONFIG_HOME/zsh/p10k.zsh"

alias magit="flatpak run org.gnu.emacs \
      --no-window-system \
      --no-init-file \
      --load $USER_CONFIG_HOME/magit/init.el #\ 
      # --eval '(progn (magit-status) (delete-other-windows))'"

# Completetion
source <(kubectl completion zsh)

# History
eval "$(mcfly init zsh)"
export MCFLY_KEY_SCHEME=vim
export MCFLY_FUZZY=true